### ISSUE TITLE
Dependency keras-vis version 0.5.0 doesn't seem to exist 

### ISSUE THREAD

**Issue by AnotherMak** [prediction2020/explainable-predictive-models#1]
When trying to install the dependencies either manually or via the `environment.yaml` I encountered a problem with `keras-vis==0.5.0`. This version doesn't seem to exist, releases of `keras-vis` go up to 0.4.1. 

Did I miss something or should I use the newest available version?
Thanks for making these models available, really appreciate it!

**Comment by prediction2020** [comment]
This should do the trick:

pip install https://github.com/raghakot/keras-vis/archive/master.zip

**Comment by AnotherMak** [comment]
Worked like a charm, thanks. 
Bit surprising that, though it obviously seems to exist, v0.5.0 isn't uploaded on PyPi.
